name: CI pipeline
run-name: CI pipeline is run by ${{ github.actor }}.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm test

      - name: Build (inject NEXT_PUBLIC_API_BASE_URL)
        run: |
          NEXT_PUBLIC_API_BASE_URL="${BACKEND_URL}" pnpm build

      - name: Verify build output
        run: |
          echo "PWD:"
          pwd
          echo "List including hidden dirs:"
          ls -la

      - name: Upload Next.js artefact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            .next/**
            public/**
          include-hidden-files: true
          retention-days: 1
          
